function mulberry32(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^(t>>>15),1|t);r^=r+Math.imul(r^(r>>>7),61|r);return((r^(r>>>14))>>>0)/4294967296}}
function setCommon(ctx,s){ctx.globalAlpha=s.opacity??1;ctx.globalCompositeOperation=s.blendMode??'source-over';ctx.strokeStyle=s.color??'#fff';ctx.fillStyle=s.color??'#fff';ctx.lineWidth=s.width??1;ctx.lineCap=s.lineCap??'round';ctx.lineJoin=s.lineJoin??'round'}
function buildPath(ctx,path=[]){ctx.beginPath();for(const p of path){switch(p.cmd){case'M':ctx.moveTo(p.x,p.y);break;case'L':ctx.lineTo(p.x,p.y);break;case'Q':ctx.quadraticCurveTo(p.cx,p.cy,p.x,p.y);break;case'C':ctx.bezierCurveTo(p.c1x,p.c1y,p.c2x,p.c2y,p.x,p.y);break;case'Z':ctx.closePath();break}}}
function applyClip(ctx,s){const b=s.clipBox;if(!Array.isArray(b)||b.length!==4)return;ctx.beginPath();ctx.rect(b[0],b[1],b[2]-b[0],b[3]-b[1]);ctx.clip()}
function drawLine(ctx,s){ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke()}
function drawCurve(ctx,s){ctx.beginPath();ctx.moveTo(s.x1,s.y1);if(s.cx2!=null)ctx.bezierCurveTo(s.cx1,s.cy1,s.cx2,s.cy2,s.x2,s.y2);else ctx.quadraticCurveTo(s.cx1,s.cy1,s.x2,s.y2);ctx.stroke()}
function drawDab(ctx,s){ctx.beginPath();ctx.arc(s.x,s.y,s.radius??Math.max(1,(s.width??1)/2),0,Math.PI*2);ctx.fill()}
function drawEllipse(ctx,s){ctx.beginPath();ctx.ellipse(s.x,s.y,s.rx??s.radius??10,s.ry??s.radius??10,s.rotation??0,0,Math.PI*2);ctx.fill()}
function drawPathFill(ctx,s){buildPath(ctx,s.path);ctx.fill(s.fillRule??'nonzero')}
function drawPathStroke(ctx,s){buildPath(ctx,s.path);ctx.stroke()}
function drawSoftDab(ctx,s){const radius=s.radius??20;const g=ctx.createRadialGradient(s.x,s.y,0,s.x,s.y,radius);g.addColorStop(0,s.color??'#fff');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(s.x,s.y,radius,0,Math.PI*2);ctx.fill()}
function drawDryBrush(ctx,s){const rand=mulberry32(s.seed??s.id??1),strands=Math.max(4,s.strands??18),dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,spread=s.spread??(s.width??12);ctx.lineWidth=Math.max(.7,(s.width??8)/strands*1.05);for(let i=0;i<strands;i++){const off=(rand()-.5)*spread,j1=(rand()-.5)*2,j2=(rand()-.5)*2;ctx.globalAlpha=(s.opacity??1)*(.3+rand()*.62);ctx.beginPath();ctx.moveTo(s.x1+nx*off+j1,s.y1+ny*off+j1);ctx.lineTo(s.x2+nx*off+j2,s.y2+ny*off+j2);ctx.stroke()}}
function hexToRgb(hex){const v=(hex??'#ffffff').replace('#','');return [parseInt(v.slice(0,2),16),parseInt(v.slice(2,4),16),parseInt(v.slice(4,6),16)]}
function mixRgb(a,b,t){return a.map((v,i)=>v*(1-t)+b[i]*t)}
function rgba(rgb,a=1){return `rgba(${Math.round(rgb[0])},${Math.round(rgb[1])},${Math.round(rgb[2])},${a})`}
function sample(ctx,x,y){const xx=Math.max(0,Math.min(ctx.canvas.width-1,Math.round(x))),yy=Math.max(0,Math.min(ctx.canvas.height-1,Math.round(y)));const d=ctx.getImageData(xx,yy,1,1).data;return [d[0],d[1],d[2]]}
function drawVariableBrush(ctx,s){const dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy),n=Math.max(2,Math.ceil(len/2.5)),w0=s.widthStart??s.width??1,w1=s.widthEnd??s.width??1;for(let i=0;i<=n;i++){const t=i/n,x=s.x1+dx*t,y=s.y1+dy*t,w=Math.max(.7,w0*(1-t)+w1*t);ctx.beginPath();ctx.arc(x,y,w/2,0,Math.PI*2);ctx.fill()}}
function drawFlatBrush(ctx,s){drawVariableBrush(ctx,s);const rand=mulberry32(s.seed??s.id??1),dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,base=s.width??10,old=ctx.globalAlpha;for(let i=0;i<3;i++){const off=(rand()-.5)*base*.65;ctx.globalAlpha=old*(.12+rand()*.10);ctx.lineWidth=Math.max(1,base*.08);ctx.beginPath();ctx.moveTo(s.x1+nx*off,s.y1+ny*off);ctx.lineTo(s.x2+nx*off,s.y2+ny*off);ctx.stroke()}ctx.globalAlpha=old}
function drawMixerBrush(ctx,s){const dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy),n=Math.max(2,Math.ceil(len/3)),pickup=s.pickup??.18,mix=s.mix??.58,deposit=s.deposit??.42;let paint=hexToRgb(s.color);for(let i=0;i<=n;i++){const t=i/n,x=s.x1+dx*t,y=s.y1+dy*t,under=sample(ctx,x,y);paint=mixRgb(paint,under,pickup);const out=mixRgb(under,paint,mix);ctx.fillStyle=rgba(out,(s.opacity??1)*deposit);ctx.beginPath();ctx.arc(x,y,Math.max(1,(s.width??8)/2),0,Math.PI*2);ctx.fill()}}
function drawSmudgeBrush(ctx,s){const dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy),n=Math.max(2,Math.ceil(len/3)),pickup=s.pickup??.10,strength=(s.strength??.30)*(s.opacity??1);let carry=sample(ctx,s.x1,s.y1);for(let i=1;i<=n;i++){const t=i/n,x=s.x1+dx*t,y=s.y1+dy*t,under=sample(ctx,x,y);ctx.fillStyle=rgba(carry,strength);ctx.beginPath();ctx.arc(x,y,Math.max(1,(s.width??8)/2),0,Math.PI*2);ctx.fill();carry=mixRgb(carry,under,pickup)}}
function drawGlaze(ctx,s){const dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy),n=Math.max(2,Math.ceil(len/3)),r=Math.max(1,(s.width??12)/2);ctx.fillStyle=s.color??'#fff';for(let i=0;i<=n;i++){const t=i/n,x=s.x1+dx*t,y=s.y1+dy*t;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
export function applyStroke(ctx,s){ctx.save();setCommon(ctx,s);applyClip(ctx,s);switch(s.brush??s.type??'line'){case'line':drawLine(ctx,s);break;case'curve':drawCurve(ctx,s);break;case'dab':drawDab(ctx,s);break;case'ellipse':drawEllipse(ctx,s);break;case'pathFill':drawPathFill(ctx,s);break;case'pathStroke':drawPathStroke(ctx,s);break;case'softDab':drawSoftDab(ctx,s);break;case'dryBrush':drawDryBrush(ctx,s);break;case'flatBrush':drawFlatBrush(ctx,s);break;case'variableBrush':drawVariableBrush(ctx,s);break;case'mixerBrush':drawMixerBrush(ctx,s);break;case'smudgeBrush':drawSmudgeBrush(ctx,s);break;case'glaze':drawGlaze(ctx,s);break;default:throw new Error(`Unknown brush: ${s.brush??s.type}`)}ctx.restore()}
