function mulberry32(seed){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^(t>>>15),1|t);r^=r+Math.imul(r^(r>>>7),61|r);return((r^(r>>>14))>>>0)/4294967296}}
function setCommon(ctx,s){ctx.globalAlpha=s.opacity??1;ctx.globalCompositeOperation=s.blendMode??'source-over';ctx.strokeStyle=s.color??'#fff';ctx.fillStyle=s.color??'#fff';ctx.lineWidth=s.width??1;ctx.lineCap=s.lineCap??'round';ctx.lineJoin=s.lineJoin??'round'}
function buildPath(ctx,path=[]){ctx.beginPath();for(const p of path){switch(p.cmd){case'M':ctx.moveTo(p.x,p.y);break;case'L':ctx.lineTo(p.x,p.y);break;case'Q':ctx.quadraticCurveTo(p.cx,p.cy,p.x,p.y);break;case'C':ctx.bezierCurveTo(p.c1x,p.c1y,p.c2x,p.c2y,p.x,p.y);break;case'Z':ctx.closePath();break}}}
function drawLine(ctx,s){ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke()}
function drawCurve(ctx,s){ctx.beginPath();ctx.moveTo(s.x1,s.y1);if(s.cx2!=null)ctx.bezierCurveTo(s.cx1,s.cy1,s.cx2,s.cy2,s.x2,s.y2);else ctx.quadraticCurveTo(s.cx1,s.cy1,s.x2,s.y2);ctx.stroke()}
function drawDab(ctx,s){ctx.beginPath();ctx.arc(s.x,s.y,s.radius??Math.max(1,(s.width??1)/2),0,Math.PI*2);ctx.fill()}
function drawEllipse(ctx,s){ctx.beginPath();ctx.ellipse(s.x,s.y,s.rx??s.radius??10,s.ry??s.radius??10,s.rotation??0,0,Math.PI*2);ctx.fill()}
function drawPathFill(ctx,s){buildPath(ctx,s.path);ctx.fill(s.fillRule??'nonzero')}
function drawPathStroke(ctx,s){buildPath(ctx,s.path);ctx.stroke()}
function drawSoftDab(ctx,s){const radius=s.radius??20;const g=ctx.createRadialGradient(s.x,s.y,0,s.x,s.y,radius);g.addColorStop(0,s.color??'#fff');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(s.x,s.y,radius,0,Math.PI*2);ctx.fill()}
function drawDryBrush(ctx,s){const rand=mulberry32(s.seed??s.id??1),strands=Math.max(4,s.strands??18),dx=s.x2-s.x1,dy=s.y2-s.y1,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,spread=s.spread??(s.width??12);ctx.lineWidth=Math.max(.5,(s.width??8)/strands*.7);for(let i=0;i<strands;i++){const off=(rand()-.5)*spread,j1=(rand()-.5)*2,j2=(rand()-.5)*2;ctx.globalAlpha=(s.opacity??1)*(.25+rand()*.7);ctx.beginPath();ctx.moveTo(s.x1+nx*off+j1,s.y1+ny*off+j1);ctx.lineTo(s.x2+nx*off+j2,s.y2+ny*off+j2);ctx.stroke()}}
export function applyStroke(ctx,s){ctx.save();setCommon(ctx,s);switch(s.brush??s.type??'line'){case'line':drawLine(ctx,s);break;case'curve':drawCurve(ctx,s);break;case'dab':drawDab(ctx,s);break;case'ellipse':drawEllipse(ctx,s);break;case'pathFill':drawPathFill(ctx,s);break;case'pathStroke':drawPathStroke(ctx,s);break;case'softDab':drawSoftDab(ctx,s);break;case'dryBrush':drawDryBrush(ctx,s);break;default:throw new Error(`Unknown brush: ${s.brush??s.type}`)}ctx.restore()}
